enum Token {
    //C++ reserved words
    tok_auto = -1,
    tok_const = -2,
    tok_double = -3,
    tok_float = -4,
    tok_int = -5,
    tok_short = -6,
    tok_struct = -7,
    tok_unsigned = -8,
    tok_break = -9,
    tok_continue = -10,
    tok_else = -11,
    tok_for = -12,
    tok_long = -13,
    tok_signed = -14,
    tok_switch = -15,
    tok_void = -16,
    tok_case = -17,
    tok_default = -18,
    tok_enum = -19,
    tok_goto = -20,
    tok_register = -21,
    tok_sizeof = -22,
    tok_typedef = -23,
    tok_volatile = -24,
    tok_char = -25,
    tok_do = -26,
    tok_extern = -27,
    tok_if = -28,
    tok_return = -29,
    tok_static = -30,
    tok_union = -31,
    tok_while = -32,
    tok_asm = -33,
    tok_dynamic_cast = -34,
    tok_namespace = -35,
    tok_reinterpret_cast = -36,
    tok_try = -37,
    tok_bool = -38,
    tok_explicit = -39,
    tok_new = -40,
    tok_static_cast = -41,
    tok_typeid = -42,
    tok_catch = -43,
    tok_false = -44,
    tok_operator = -45,
    tok_template = -46,
    tok_typename = -47,
    tok_class = -48,
    tok_friend = -49,
    tok_private = -50,
    tok_this = -51,
    tok_using = -52,
    tok_const_cast = -53,
    tok_inline = -54,
    tok_public = -55,
    tok_throw = -56,
    tok_virtual = -57,
    tok_delete = -58,
    tok_mutable = -59,
    tok_protected = -60,
    tok_true = -61,
    tok_wchar_t = -62,
    tok_and = -63,
    tok_bitand = -64,
    tok_compl = -65,
    tok_not_eq = -66,
    tok_or_eq = -67,
    tok_xor_eq = -68,
    tok_and_eq = -69,
    tok_bitor = -70,
    tok_not = -71,
    tok_or = -72,
    tok_xor = -73,

    //C^2 reserved words
    tok_def = -74,
    tok_extern = -75,
    tok_as = -76,

    //C^2 types
    tok_list = -77,
    tok_string = -83,

    //C^2 operators
    tok_in = -78,
    tok_equals = -79,

    //primary
    tok_identifier = -80,
    tok_number = -81,
    tok_list_decl = -82,
    tok_string_decl = -84,

}
